In [17]:
import pandas as pd  

In [18]:
import numpy as np

Basic filtering

In [19]:
ages = np.array([25 , 30 , 18 , 35 , 22 , 40 , 17])

adults = ages[ages >= 18]

print(adults)

[25 30 18 35 22 40]


In [20]:
adults_age = ages[(ages > 20) & (ages < 35)]

print(adults_age)

[25 30 22]


In [21]:
names = np.array(["Rahul" , "Amit",  "Alice" , "Pooja" , "Carlie" , "Bob"])

selected_name = names[np.char.startswith(names , "A") | np.char.startswith(names , "P")]

print(selected_name)

['Amit' 'Alice' 'Pooja']


Basic Masking for Selection

In [22]:
temp = np.array([28 , 32 , 35 , 30 , 22 , 38])

is_hot = temp > 30

hot_temp = temp[is_hot]

print(temp)
print(is_hot)
print(hot_temp)

[28 32 35 30 22 38]
[False  True  True False False  True]
[32 35 38]


Masking Modification

In [23]:
temp[is_hot] = 31

print(temp)

[28 31 31 30 22 31]


np.where()

In [24]:
scores = np.array([68 , 81 , 78 , 90 , 55 , 78])

# If score >= 75 -> Pass , otherwise Fail

grades = np.where(scores >= 75 , "Pass" , "")

print(scores)
print(grades)

[68 81 78 90 55 78]
['' 'Pass' 'Pass' 'Pass' '' 'Pass']


Reshaping 1D and 2D

In [25]:
num_1d = np.array([1 , 2 , 3 , 4])

num_2d = num_1d.reshape(1 , 4)

print(num_1d)

print(num_2d)

[1 2 3 4]
[[1 2 3 4]]


Broadcasting to an array

In [26]:
prices = np.array([10 , 20 , 30])

# add 5 to every element

new_prices = prices + 5

print(prices)

print(new_prices)

[10 20 30]
[15 25 35]


Broadcasting 1D to a 2D

In [27]:
sales = np.array([[10 , 20] , [15 , 25] , [12 , 18]])

add_value = np.array([2 , 3 , 1])

print(sales)

print(add_value)

[[10 20]
 [15 25]
 [12 18]]
[2 3 1]


In [28]:
bonues_col =add_value.reshape(3 , 1)

sales_with_bonues = sales + bonues_col

print(bonues_col)

[[2]
 [3]
 [1]]


In [29]:
print(sales_with_bonues)

[[12 22]
 [18 28]
 [13 19]]
